"""empty message

Revision ID: 63caf8a730f6
Revises: ec5eca7f60b8
Create Date: 2026-02-26 20:41:47.475767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63caf8a730f6'
down_revision = 'ec5eca7f60b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked__characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_character'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked__characters')
    # ### end Alembic commands ###
